AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue Data Catalog - Database and Crawlers for Data Pipeline'

Parameters:
  RawBucketName:
    Type: String
    Description: Name of the raw data S3 bucket
    Default: data-lake-raw-zone-616129051451
  
  ProcessedBucketName:
    Type: String
    Description: Name of the processed data S3 bucket
    Default: data-lake-processed-zone-616129051451

Resources:
  # Glue Database - Central metadata repository
  DataPipelineDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: data_pipeline_catalog
        Description: 'Central metadata catalog for data pipeline - contains table definitions for sales, customers, products, and processed datasets'
        LocationUri: !Sub 's3://${RawBucketName}/'
        Parameters:
          'classification': 'parquet'
          'environment': 'development'
          'project': 'data-pipeline'

  # IAM Role for Glue Crawlers
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DataPipelineGlueCrawlerRole
      Description: 'Allows Glue crawlers to read S3 data and write to Glue Data Catalog'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                Resource:
                  - !Sub 'arn:aws:s3:::${RawBucketName}'
                  - !Sub 'arn:aws:s3:::${RawBucketName}/*'
                  - !Sub 'arn:aws:s3:::${ProcessedBucketName}'
                  - !Sub 'arn:aws:s3:::${ProcessedBucketName}/*'
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:/aws-glue/*'

  # Crawler for Sales Data
  SalesDataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: DataPipelineDatabase
    Properties:
      Name: sales-data-crawler
      Description: 'Crawls sales transaction data in Parquet format from raw zone'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref DataPipelineDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${RawBucketName}/sales/'
            Exclusions:
              - '**.json'  # Only crawl Parquet files
              - '**_$folder$'  # Exclude S3 metadata files
      SchemaChangePolicy:
        UpdateBehavior: LOG
        DeleteBehavior: LOG
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Partitions": {"AddOrUpdateBehavior": "InheritFromTable"}
          },
          "Grouping": {
            "TableGroupingPolicy": "CombineCompatibleSchemas"
          }
        }
      Schedule:
        # Run daily at 3 AM UTC (1 hour after EventBridge triggers Lambda)
        ScheduleExpression: 'cron(0 3 * * ? *)'
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY
      Tags:
        Environment: Development
        Project: DataPipeline
        DataSource: Sales

  # Crawler for Customers Data
  CustomersDataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: DataPipelineDatabase
    Properties:
      Name: customers-data-crawler
      Description: 'Crawls customer demographic data in Parquet format from raw zone'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref DataPipelineDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${RawBucketName}/customers/'
            Exclusions:
              - '**.json'
              - '**_$folder$'
      SchemaChangePolicy:
        UpdateBehavior: LOG
        DeleteBehavior: LOG
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Partitions": {"AddOrUpdateBehavior": "InheritFromTable"}
          },
          "Grouping": {
            "TableGroupingPolicy": "CombineCompatibleSchemas"
          }
        }
      Schedule:
        ScheduleExpression: 'cron(0 3 * * ? *)'
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY
      Tags:
        Environment: Development
        Project: DataPipeline
        DataSource: Customers

  # Crawler for Products Data
  ProductsDataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: DataPipelineDatabase
    Properties:
      Name: products-data-crawler
      Description: 'Crawls product catalog data in Parquet format from raw zone'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref DataPipelineDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${RawBucketName}/products/'
            Exclusions:
              - '**.json'
              - '**_$folder$'
      SchemaChangePolicy:
        UpdateBehavior: LOG
        DeleteBehavior: LOG
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Partitions": {"AddOrUpdateBehavior": "InheritFromTable"}
          },
          "Grouping": {
            "TableGroupingPolicy": "CombineCompatibleSchemas"
          }
        }
      Schedule:
        ScheduleExpression: 'cron(0 3 * * ? *)'
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY
      Tags:
        Environment: Development
        Project: DataPipeline
        DataSource: Products

  # Crawler for Automated Ingestion Data (JSON from Lambda)
  AutomatedIngestionCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: DataPipelineDatabase
    Properties:
      Name: automated-ingestion-crawler
      Description: 'Crawls JSON data generated by Lambda ingestion function'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref DataPipelineDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${RawBucketName}/automated-ingestion/'
            Exclusions:
              - '**_$folder$'
      SchemaChangePolicy:
        UpdateBehavior: LOG
        DeleteBehavior: LOG
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Partitions": {"AddOrUpdateBehavior": "InheritFromTable"}
          },
          "Grouping": {
            "TableGroupingPolicy": "CombineCompatibleSchemas"
          }
        }
      Schedule:
        ScheduleExpression: 'cron(0 3 * * ? *)'
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY
      Tags:
        Environment: Development
        Project: DataPipeline
        DataSource: AutomatedIngestion

Outputs:
  DatabaseName:
    Description: 'Glue Database Name'
    Value: !Ref DataPipelineDatabase
    Export:
      Name: GlueDatabaseName

  CrawlerRoleArn:
    Description: 'IAM Role ARN for Glue Crawlers'
    Value: !GetAtt GlueCrawlerRole.Arn
    Export:
      Name: GlueCrawlerRoleArn

  SalesCrawlerName:
    Description: 'Sales Data Crawler Name'
    Value: !Ref SalesDataCrawler
    Export:
      Name: SalesCrawlerName

  CustomersCrawlerName:
    Description: 'Customers Data Crawler Name'
    Value: !Ref CustomersDataCrawler
    Export:
      Name: CustomersCrawlerName

  ProductsCrawlerName:
    Description: 'Products Data Crawler Name'
    Value: !Ref ProductsDataCrawler
    Export:
      Name: ProductsCrawlerName

  AutomatedIngestionCrawlerName:
    Description: 'Automated Ingestion Crawler Name'
    Value: !Ref AutomatedIngestionCrawler
    Export:
      Name: AutomatedIngestionCrawlerName
